---
title: "A Data Analyst in the Making"
description: "<i>Graphical excellence is that which gives to the viewer the greatest number of ideas in the shortest time with the least ink in the smallest space.”</i><br> - Edward Tufte <br><br>" 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

This blog is created & updated as a part of the coursework of Visual Analytics and Applications, taught by [Professor Kam Tin Seong](https://www.smu.edu.sg/faculty/profile/9618/KAM-Tin-Seong) at Singapore Management University.

The posts are critiques and re-design of visualizations.

To quote Professor Kam:
_The purpose of the makeover is to improve on the original visualization. Focus on what works, what doesn’t work, why those things don’t work, and how you made it better. You should try stick to the fields in the data set provided and improve upon the original visualization. However, if supplementing the data helps you tell a better story, go for it!_


As of 27th May 2021, the first Data Viz Visualization has been posted. 
This is a re-design of the Merchandise Trade data of Singapore for 2019 & 2020. 





The design of the blog was created with some graphics and CSS:

- Image attributes:

  <a href="https://storyset.com/business">Illustration by Freepik Storyset</a>

  <a href="https://slidesgo.com/theme/economics-thesis#search-economics&position-0&results-4">Slidesgo.com</a>

- CSS Inspiration:

  <a hred="https://csspoint101.com/30-css-animated-background/"> Designed by Carpe Numidium</a>

